_wandb:
    value:
        cli_version: 0.27.0
        code_path: code/src/train.py
        e:
            5v9tdq53tk42wa2d7bux6tld232cacd6:
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "29348499456"
                        used: "22415454208"
                email: ashanthan.a.mudaly@student.uts.edu.au
                executable: /usr/bin/python3
                git:
                    commit: ed259184ddba53b22de4acaa1e77e5c9b352284e
                    remote: https://github.com/AshMudaly/Rally-Racing.git
                host: ashmu-laptop
                memory:
                    total: "32919748608"
                os: Linux-6.8.0-124-generic-x86_64-with-glibc2.35
                program: /home/ashmu/41118_ws/project/Rally-Racing/src/train.py
                python: CPython 3.10.12
                root: /home/ashmu/41118_ws/project/Rally-Racing
                startedAt: "2026-05-31T12:52:46.825422Z"
                writerId: 5v9tdq53tk42wa2d7bux6tld232cacd6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 22
                - 35
            "4": 3.10.12
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
batch_size:
    value: 256
device:
    value: cpu
ent_coef:
    value: 0.01
learning_rate:
    value: 0.0003
n_envs:
    value: 8
policy_kwargs:
    value:
        net_arch:
            - 256
            - 256
scenario:
    value: phase2
total_timesteps:
    value: 300000
